### PR TITLE
Fix environment bug in bulk submission

### LINKED ISSUE #98: Issue with environment resolution while running in bulk mode
This is a stripped down version of the bug reported by @cwhittaker1000

with `src.R` containing:

```r
thing <- R6::R6Class(
  "thing",
  public = list(fn = function(x) x + 1))

f <- function(x) {
  thing$new()$fn(x)
}
```

```
id <- ids::random_id(1, 4)
r <- rrq::rrq_controller$new(id)
r$envir(rrq::rrq_envir(sources = c("src.R")))
w1 <- rrq::rrq_worker$new(r$queue_id)

## Works fine:
t1 <- r$enqueue(f(1))
w1$step(TRUE)
r$task_result(t1)

## This works in a blocking worker:
source("src.R")
g1 <- r$lapply(1, f, timeout_task_wait = 0)
w1$step(TRUE)
r$task_result(g1$task_ids)

## Also works fine in a real worker:
w2 <- rrq::rrq_worker_spawn(r)
t2 <- r$enqueue(f(1))
r$task_wait(t2) # 2 as expected

## But this fails in a real worker:
g2 <- r$lapply(1, f, timeout_task_wait = 10)
```

The error object:

```
<rrq_task_error>
  from:   `2110a78728ee57f02b634a8498f1845c`(1)
  error:  object 'thing' not found
  queue:  ec732816
  task:   e90ce910790f9964ffbc6ededff04a6c
  status: ERROR
  * To throw this error, use stop() with it
  * This error has a stack trace, use '$trace' to see it
```

the trace is not very illuminating:

```

  1. ├─base::tryCatch(...)
  2. │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  3. │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  4. │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  5. ├─base::withCallingHandlers(...)
  6. ├─base::eval(expr, envir)
  7. │ └─base::eval(expr, envir)
  8. │   └─global `2110a78728ee57f02b634a8498f1845c`(1)
  9. └─base::.handleSimpleError(...) at src.R:6:2
 10.   └─rrq (local) h(simpleError(msg, call))
```

### PR DESCRIPTION
**Pull request by richfitz**
The issue here is sort of described in the issue (#98) and in the test case. Basically, in the most common real-world situation (functions sourced globally) any function we use via lapply or enqueue bulk ends up with an environment that means that it cannot find any values referred to using lexical scope! I think that callr does this nicely by passing in the `package` environment, it's a hard problem really.

Here, we just fix up the environments of any functions that come through anonymously.

Fixes #98

### CODE REVIEW

File: tests/testthat/test-bulk.R [hunk 1]
```diff
@@ -349,3 +349,31 @@ test_that("Set completion keys", {
                       function(k) list_to_character(obj$con$LRANGE(k, 0, -1))),
                as.list(grp$task_ids))
 })
+
+
+test_that("allow referring to locals in bulk", {
+  obj <- test_rrq("funs-bulk.R")
+  obj$envir(rrq::rrq_envir(sources = c("funs-bulk.R")))
+
+  ## We can't easily the previous error with a blocking worker because:
```
Comment (r-ash) [inline tests/testthat/test-bulk.R:358]:
```suggestion
  ## We can't easily recreate the previous error with a blocking worker because:
```

Comment (r-ash) [reply tests/testthat/test-bulk.R:358]: Actually maybe worth being explicit about what the previous error is?

**Review by r-ash — APPROVED** [review]
What's the difference between how we set up the environment for a single task submission and for bulk submission? Not obvious to me why this works in single task submission and not in bulk submission.
